### ISSUE TITLE
Can "server_url" be a link with a path?

### ISSUE THREAD

**Issue by NicolasDorier** [shesek/wordpress-lightning-paywall#5]
@shesek I plan to integrate lightning-charge to BTCPay as an option.
But, because we don't want to require users to open new ports, we use URL rewriting on nginx. (like https://btcpay.example.com/clightning-charge/btc/)

Will this work fine with wordpress lightning publisher?

**Comment by pieman64** [comment]
@NicolasDorier if you need anyone to test things just give me a shout.

**Comment by shesek** [comment]
Yes, it should work alright. But note that Lightning Publisher also uses the checkout page provided by Lightning Charge as an iframe, which I guess would add more complexity on your side?

Of the Charge-based Lapps I wrote, only Lightning Publisher and nanotip rely on the embedded checkout page. The other Lapps display payments information on their own and rely solely on the API.

**Comment by NicolasDorier** [comment]
well it seems easy for me to steal as long as I can put them in any path I want.

**Comment by shesek** [comment]
Then yes, you can. Note that you have two configurable URLs: `server_url`which is used for talking with the API, and `public_url` which is used for the iframe.

**Comment by pieman64** [comment]
Any news @NicolasDorier on the publisher mods?

**Comment by NicolasDorier** [comment]
no, have not start working on the API in btcpay

**Comment by NicolasDorier** [comment]
@pieman64 it is done, please try https://twitter.com/BtcpayServer/status/1076025576845017088

**Comment by pieman64** [comment]
Thanks @NicolasDorier I will switch my node from LND to c-lightning in the coming days and try it out.

**Comment by NicolasDorier** [comment]
@pieman64 check https://www.youtube.com/watch?v=ZbM3jcxau0o 

Closing this issue

**Comment by pieman64** [comment]
Thanks @NicolasDorier we set it up a few days ago on our site after following developments in the BTCpay Slack channel.

https://buycryptonewsarticles.com/ethereum-etc-faucet/

**Comment by NicolasDorier** [comment]
Very cool :D
Though paying for a ethereum article via BTC with lightning won't get you lot's of customers aha.

**Comment by pieman64** [comment]
@NicolasDorier never thought of that. We simply added Publisher to an article we had written previously. I am following this issue https://github.com/btcpayserver/btcpayserver/issues/50 in the hope that ERC tokens will be available at some point in the future.
